fixed an issue that would cause crawlme to encounter an error when handling incorrect html (<a> without href attribute)
Caught exception: TypeError: Parameter 'url' must be a string, not object
TypeError: Parameter 'url' must be a string, not object


This would happen because url = null in the case where the href attribute is not defined in the HTML